### PR TITLE
Use freebsd-version to get the OS version

### PR DESCRIPTION
**Pull request by ghost**
`uname -r` reports the version/patch level of the kernel, `freebsd-version` gives us the version/patch level of the whole system.

It also allows the right version to be reported when run from inside a jail.

### CODE REVIEW

**Comment by dlangille** [comment]
So I'm not the only user. :)

**Comment by ghost** [comment]
😁 

I've been trying to find a simple solution to tracking OS updates and vulnerable packages for 50+ jails that isn't based on cron and floods of e-mail notifications. SamDrucker is the start to killing multiple birds with one stone.

**Comment by dlangille** [comment]
From a jail:

```
$ freebsd-version
12.2-RELEASE-p2
$ uname -r
12.2-RELEASE-p1
$ 
```

That's OK by me.

**Comment by dlangille** [comment]
@fyfe see also https://github.com/dlangille/SamDrucker/commit/aeee33c4ef16c56b2ccc27c4823b8c9ea3cc1802 where I changed to using full pathnames.

**Comment by dlangille** [comment]
Testing here.

Before:

```
samdrucker=# select * from host where name = 'dev-ingress01.int.unixathome.org';
 id  |               name               |   os    |     version     |                                    repo                                    |        date_updated        | enabled 
-----+----------------------------------+---------+-----------------+----------------------------------------------------------------------------+----------------------------+---------
 100 | dev-ingress01.int.unixathome.org | FreeBSD | 12.2-RELEASE-p1 | pkg+http://fedex.int.unixathome.org/packages/121amd64-default-master-list/ | 2021-01-27 03:40:07.467557 | t
(1 row)
```

After:
```
samdrucker=# select * from host where name = 'dev-ingress01.int.unixathome.org';
 id  |               name               |   os    |     version     |                                    repo                                    |        date_updated        | enabled 
-----+----------------------------------+---------+-----------------+----------------------------------------------------------------------------+----------------------------+---------
 100 | dev-ingress01.int.unixathome.org | FreeBSD | 12.2-RELEASE-p2 | pkg+http://fedex.int.unixathome.org/packages/121amd64-default-master-list/ | 2021-01-27 22:47:18.062067 | t
(1 row)
```

**Comment by dlangille** [comment]
@fyfe Working for you? I updated the FreeBSD packages same day.

**Comment by ghost** [comment]
Yes that's working, thanks.

**Pull request merged**
